CHECA_GRAVACAO:
/CHECAGEM@DE@ERRO
ษออออออออออออออออออออออออออต A T E N €  O  !!! ฦออออออออออออออออออออออออป
บ                                                                        บ
บ Por problemas de ordem tcnica, a  gravao  desta  operao  No  FOI บ
บ                                                                        บ
บ REALIZADA COM SUCESSO, devendo ser refeita posteriormente !            บ
บ                                                                        บ
บ Entre em contato com a CONAM  (011) 3218-1405 setor de suporte  o mais บ
บ                                                                        บ
บ urgente possกvel .                                                     บ
บ                                                                        บ
บ IMPORTANTE : Anote O ERRO, SEU NฃMERO (que sero mostrados a seguir) e บ
บ              QUAL PROGRAMA DO SISTEMA VOC EST  UTILIZANDO !           บ
บ                                                                        บ
ศอต Pressione qualquer tecla para mostrar a tela  com os dados do erro ฦอผ
/*

PAGE SET CHECAGEM@DE@ERRO AT 07 03 COLORS IT_COR_TARJA IT_COR_TITULO

ABORT_TRANSACTION
UNLOCK
PAGE CHECAGEM@DE@ERRO
GOTOXY 25 00
PAUSE
ERROR LASTERR
INDICATE ERR FALSE
ON ERROR OFF
RETURN INICIO
